version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

    groups:
      node-dependencies:
        patterns:
          -"*"

    ignore:
      - dependency-name: "lodash"
        versions:
          - "4.17.1"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "deps"

    labels:
      - "dependencies"
      - "security"

    reviewers:
      - "@shanconsult1987"
